# Thanks to https://github.com/ading2210/badrecovery for the orginal badrecovery workflow file
on: workflow_dispatch
name: build

jobs:
  build:
    permissions:
      contents: write
    
    strategy: 
      matrix:
        board: [ambassador, asuka, auron-paine, auron-yuna, banjo, banon, bob, brask, brya, buddy, buddy-cfm, butterfly, candy, caroline, cave, celes, chell, clapper, constitution, coral, cyan, daisy, daisy-skate, daisy-spring,  edgar, elm, endeavour, enguarde, eve, excelsior, expresso, falco, falco-li, fizz, fizz-cfm, gandof, glimmer, gnawty, grunt, guado, guado-cfm, guybrush, hana, hatch, heli, jacuzzi, kalista, kalista-cfm, kefka, kevin, kip, kukui, lars, leon, link, lulu, lumpy, mccloud, monroe, nami, nautilus, ninja, nyan-big, nyan-blaze, nyan-kitty, octopus, orco, panther, parrot, parrot-ivb, peach-pi, peach-pit, peppy, puff, pyro, quawks, reef, reks, relm, reven, rikku, rikku-cfm, samus, sand, scarlet, sentry, setzer, snappy, soraka, squawks, stout, strongbad, stumpy, sumo, swanky, terra, tidus, tricky, ultima, veyron-fievel, veyron-jaq, veyron-jerry, veyron-mickey, veyron-mighty, veyron-minnie, veyron-speedy, veyron-tiger, volteer, winky, wizpig, wolf, x86-alex, x86-alex-he, x86-mario, x86-zgb, x86-zgb-he, zako, zork
]

    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 32768
          swap-size-mb: 64
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: download repo
        uses: actions/checkout@v4
      
      - name: run build
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler pv
          sudo apt-get install -y pv
          sudo pip3 install protobuf six --break-system-packages
          sudo QUIET=1 bash buildfull_badsh1mmer.sh "${{ matrix.board }}"

      - name: create release
        uses: ading2210/gh-large-releases@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: badsh1mmer-*.bin
          make_latest: true
